packages:
  - block
  - model
  - software/aggregate-clonotypes
  - test
  - ui
  - workflow

catalog:
  "@milaboratories/graph-maker": 1.4.8
  "@milaboratories/helpers": 1.14.2
  "@milaboratories/ts-builder": 1.5.2
  "@milaboratories/ts-configs": 1.2.3
  "@platforma-sdk/workflow-tengo": 6.6.5
  "@platforma-sdk/block-tools": 2.11.10
  "@platforma-sdk/model": 1.79.17
  "@platforma-sdk/ui-vue": 1.79.17
  "@platforma-sdk/test": 1.79.19
  "@platforma-sdk/tengo-builder": 4.0.15
  "@platforma-sdk/package-builder": 3.14.0
  "@platforma-sdk/blocks-deps-updater": 2.2.0

  "@platforma-open/milaboratories.runenv-python-3": 1.7.8

  "turbo": 2.8.11

  "shx": 0.4.0
  "@changesets/cli": 2.29.8
  vue: 3.5.24
  vitest: ~4.0.18
